apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "scaler-kubernetes-webhook.acme.com"
webhooks:
  - name: "scaler-kubernetes-webhook.acme.com"
    # Avoid chicken-egg problem with our webhook deployment.
    objectSelector:
      matchExpressions:
      - key: app
        operator: NotIn
        # This is the label 'app' of the Webhook deployment.yaml
        # eg. app: scaler-kubernetes-webhook
        values: ["scaler-kubernetes-webhook"]    
    rules:
      - apiGroups:   ["keda.sh"]
        apiVersions: ["v1", "v1alpha1"]
        operations:  ["CREATE"]
        resources:   ["scaledjobs", "scaledobjects"]
        scope:       "*"
    clientConfig:
      service:
        namespace: webhook
        name: scaler-kubernetes-webhook
        path: /validate-pods
        port: 443
      caBundle: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRekNDQWl1Z0F3SUJBZ0lVWllYaFFRdzVO
        M1R3VkRyNkljeXl0cHJtUVhZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd01URUxNQWtHQTFVRUJoTUNR
        VlV4SWpBZ0JnTlZCQU1NR1hOallXeGxjaTFyZFdKbGNtNWxkR1Z6TFhkbApZbWh2YjJzd0hoY05N
        alV3TXpBMk1ERTBNelEyV2hjTk1qWXdNekEyTURFME16UTJXakF4TVFzd0NRWURWUVFHCkV3SkJW
        VEVpTUNBR0ExVUVBd3daYzJOaGJHVnlMV3QxWW1WeWJtVjBaWE10ZDJWaWFHOXZhekNDQVNJd0RR
        WUoKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSTJXbGJUNmZibSttcFBqMGJXTDFJ
        WlhpWEIwc1NFUApPV09VWEMwWVc1NE1UN3F3TGVsQzhyNFNVeXo0aWUvWVpSUWsycGlPdW11ajg4
        MEtjaGtqT3czRDhhdzZhK1BaCnl2QnVpN0U1T000UDNrK21BWjhqNE5xb3d6RmRpdkM2Qm95Ulg2
        UVk1MDJTNDcxR05BZG5jUDBFMEI0UXF1eXQKSnRnWmVrQWZydUVtQ1VMWG96cjhHYWUrZHBubC9D
        eEE1V1E0TUxGZ1o1cjFmVDZuRUVVSnVwS05vVlVaeWhZUgo3bTF2RkVtdlB3ZCtjNmd5bWVSMmJs
        VUkyL1JzdkJrOXBmZWVidXdmUElHem1CTmZTcVEvZDVZN0hOUGhXaWV4CkxoTnpMU3VTOFpnbVN5
        WWhnd2VYSWx2UmRyOEdkdVkxcWhUMUZtSC9Ed3VoUWFKYktKOTBUWkVDQXdFQUFhTlQKTUZFd0hR
        WURWUjBPQkJZRUZBRzRrTEdLeFVMcVlUMXZRaUowenduNmIrRitNQjhHQTFVZEl3UVlNQmFBRkFH
        NAprTEdLeFVMcVlUMXZRaUowenduNmIrRitNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29a
        SWh2Y05BUUVMCkJRQURnZ0VCQUQwVE55Q3VRWm91M2drMnc5Z1FnLzFFbjFoMlQ3cHczMUptOTBY
        YlRMS0lWc1VZMUhnRUcrc3kKSHAyRzNjSWgveU13My9abXhBZTI0bmtXV2NzYmk0bkpkdjdKZlNI
        NzNQR1pZR3ltZmNwWXZFd1c4cUF6OUU0aApsM3ZMZG1CODBkRWl1ME9iQkFWMTBHK1JFdEpURm44
        OEwrdlFiQjZJU3ZOSHFkRVdDcWJLcTVYcDV1YWhuMzB4Cmg1aGVoa2pRa0NTYUhxZ1Rna3lHU3F3
        WWdTM3l4S0ZKZHJueTI1QnlRSHBpTnFBMVYzakxDZkNZQkVBRFpyZWQKODNBVHlGZ1BiWUY0NHZi
        N1NoczF1S1J3V1FENjhlRDkzZUpKWGpSNWpiZDlOOXViSGg3ZmNGbXVkUlRpdWdmVQpZSEg5MTVu
        VktYQlhtTWFhUW1HQThaVGptOWdEdkhJPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 2