apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "scaler-kubernetes-webhook.acme.com"
webhooks:
  - name: "scaler-kubernetes-webhook.acme.com"
    namespaceSelector:
      matchLabels:
        admission-webhook: enabled
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["deployments"]
        scope: "*"
    clientConfig:
      service:
        namespace: default
        name: scaler-kubernetes-webhook
        path: /mutate-pods
        port: 443
      caBundle: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRekNDQWl1Z0F3SUJBZ0lVQnY5Q2N4QmpQ
        Vkg3VmtuVHlPLzhKZDF0YnNBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd01URUxNQWtHQTFVRUJoTUNR
        VlV4SWpBZ0JnTlZCQU1NR1hOallXeGxjaTFyZFdKbGNtNWxkR1Z6TFhkbApZbWh2YjJzd0hoY05N
        alV3TXpBek1ERTBNREkzV2hjTk1qWXdNekF6TURFME1ESTNXakF4TVFzd0NRWURWUVFHCkV3SkJW
        VEVpTUNBR0ExVUVBd3daYzJOaGJHVnlMV3QxWW1WeWJtVjBaWE10ZDJWaWFHOXZhekNDQVNJd0RR
        WUoKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTkFJVHJCa3kzcGJNTVZ2eEFQVTlK
        SXh4MWVRZGZkNwozVitVcE1MbWhCbGdXZS85bDVDNlhKOFZ2N2RUbWt2blJSOGJmVlNCaTZIMjZL
        R2dtYk5kRUFuK0dqK3p1MDhzClNkTmh5TzJoSjI0RXl1d2RGZkZyZXVyaVhrVWQyTzNweURHd1Jv
        NW9WN2VncG9BSks1ZHhRWW9vVEVhb2pQcCsKVjV4ZkRWWnFjLzB3eEp2VjBGekIzR2FHZHcrNDc3
        NGdsVmxUR1FUeENiUEQ3b2F4TjNQVXhRbW84Mmo0M0FXOQpVL1JYTXAxRGFCV3NqbWZSbWdNa0t5
        emZyQS9DZGNXeTY5ejMvZTU1YjdFcHlvd1M0cXQveWIydDA5RHVNV2dsCnpkNVMxdzMzNmphWDlv
        OXZKRGlTbUpIalNjUlhQbVk0V0lkdnkwM3dTTE9aY0dQV0hRdVl3WE1DQXdFQUFhTlQKTUZFd0hR
        WURWUjBPQkJZRUZGOHNoTGQxNlJpbUpKMlhlMlBXQ2xRSHlHTFJNQjhHQTFVZEl3UVlNQmFBRkY4
        cwpoTGQxNlJpbUpKMlhlMlBXQ2xRSHlHTFJNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29a
        SWh2Y05BUUVMCkJRQURnZ0VCQU0zbW9hWmZlNUdxWjJ6aldpVitsOHRGS0NpWi9zYUErQjFmeVcr
        YTlQT2Z4UUtWekhSYXd5eVEKRDQzRWphY1ZNU1RPWVg4aFBWWDkvN2R2RjNtb3E3ZGVuaVVBclJG
        VXVCQUpYZHhQSC9UdUJ5V0Z5WkZaY1ptSgp1L1lVZ0ZXeWZGZ2hGS3lZN0hVMXM1UEhIRStjdjBX
        ZGpCZklIMkZvSU85cEx4QVFEblVGS3dyeVVydU9LSjlsCm9KRU8xQUxPRTJiQlR0R0NteXhYYUVq
        VVEwaXRlaFZhZ3piZjVJb25XNi8wZVkrWktrVXdJem5SMFRBWHg0TE0KSjNRUUxYQjQ0RHR2K1dv
        cXg2WmhzRC9WQnFrQ2JPRDE3ekJwcDBESVZjYVBIcXlRakhEVDZheUlXOTJMV3AzUQpDbWtZTk9V
        UVZtMWJ5bGVocnhPZ3kyTGlFVWttREpNPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 2